#!/usr/bin/env node
let process = require('process')
let child_process = require('child_process')

const { ESLint } = require("eslint");

function exec(name) {
  return new Promise(function (resolve) {
    child_process.exec(name, resolve)
  })
}

(async function main() {
  // 1. Create an instance.
  const eslint = new ESLint();

  // 2. Lint files.
  await exec('git stash push -k')
  const results = await eslint.lintFiles(["index.js"]);
  await exec('git stash pop')

  // 3. Format the results.
  const formatter = await eslint.loadFormatter("stylish");
  const resultText = formatter.format(results);

  // 4. Output it.
  console.log(resultText);

  for (const result of results) {
      if (result.errorCount) {
        process.exit(1)
      }
  }
})().catch((error) => {
  process.exitCode = 1;
  console.error(error);
});